database:
  url: "jdbc:mysql://localhost:3306/bukkitwebintegration?useSSL=true&requireSSL=false"
  username: "root"
  password: "root"
  table:
    players: "players"
    player_credentials: "player_credentials"

auth:
  enabled: true
  mandatory_register: true
  mandatory_login: true
